name: Compatibility with pynxtools

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pynx_compatibility:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pynxtools_versions: ["master"]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv pip install --system coverage coveralls
      - name: Install pynxtools-xps
        run: |
          uv pip install --system .[dev]
      - name: Install pynxtools version ${{ matrix.pynxtools_versions }}
        run: |
         if [ "${{ matrix.pynxtools_versions }}" == "master" ]; then
           uv pip install --system pynxtools@git+https://github.com/FAIRmat-NFDI/pynxtools@${{ matrix.pynxtools_versions }}
         else
          uv pip install --system pynxtools==${{ matrix.pynxtools_versions }}
         fi
      - name: Run tests
        run: |
          pytest tests/.